// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use bson::doc;
use chrono::DateTime;
use chrono::Utc;
use diesel::Queryable;
use serde::Serialize;

#[derive(Queryable, Debug, Serialize)]
pub struct User {
    pub id: String,
    pub name: String,
    pub email: String,
    pub password: String,
    // #[serde(with = "bson::serde_helpers::chrono_datetime_as_bson_datetime")]
    // #[serde(skip_serializing)]
    // pub created_at: Option<DateTime<Utc>>,
    // #[serde(skip_serializing)]
    // pub updated_at: Option<DateTime<Utc>>,
}

#[derive(Queryable, Debug, Serialize)]
pub struct Transaction {
    pub id: String,
    pub sender_id: String,
    pub receiver_id: String,
    pub amount: f32,
    // #[serde(skip_serializing)]
    // pub created_at: DateTime<Utc>,
    // #[serde(skip_serializing)]
    // pub received_at: DateTime<Utc>,
}
